version: '3.2'

services:
  catalogapi:
    build:
      context: .
      dockerfile: Sogeti.WSDocker2019.ComposeService/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "passWor01lososo34"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"